version: '3.8'

services:
  db:
      image: postgres:15-alpine
      container_name: database_postgres
      environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: zxcbank_db
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data
      restart: unless-stopped

  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      environment:
          PGADMIN_DEFAULT_EMAIL: admin@zxcbank.com
          PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "5050:80"
      depends_on:
        - db
      restart: unless-stopped

  redis:
      image: redis:7-alpine
      container_name: redis
      ports:
        - "6379:6379"
      restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_mb
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   # Порт для подключения из .NET кода
      - "15672:15672" # Порт для веб-интерфейса управления
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  seq:
    image: datalust/seq:latest
    container_name: seq_logs
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=DontFuckMyBrainAndTakeThisPassword!10
    ports:
      - "5341:80"
    restart: unless-stopped

  backend:
        build:
            context: .
            dockerfile: Dockerfile.backend
        container_name: backend_server
        environment:
          - ConnectionStrings__ZxcBankDb=Host=db;Port=5432;Database=zxcbank_db;Username=postgres;Password=postgres;
          - ConnectionStrings__Redis=redis:6379
          - ConnectionStrings__RabbitMq=amqp://guest:guest@rabbitmq:5672/
          - SEQ_URL=http://seq:80
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=http://+:8080
        ports:
          - "8080:8080"
        depends_on:
          rabbitmq:
            condition: service_healthy
          db:
            condition: service_started
          redis:
            condition: service_started
          seq:
            condition: service_started
        restart: unless-stopped

  frontend:
      build: 
          context: ./src/Web/clientApp
          dockerfile: Dockerfile
      container_name: application_frontend
      ports:
        - "3000:80"
      depends_on:
        - backend
      restart: unless-stopped

volumes:
  pgdata: