name: Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /root/ZXC
            git pull origin main
            
            echo "DB_USER=${{ secrets.PROD_DB_USER }}" > .env
            echo "DB_PASSWORD=${{ secrets.PROD_DB_PASSWORD }}" >> .env
            echo "DB_NAME=${{ secrets.PROD_DB_NAME }}" >> .env
            echo "RABBITMQ_USER=${{ secrets.PROD_RABBITMQ_USER }}" >> .env
            echo "RABBITMQ_PASSWORD=${{ secrets.PROD_RABBITMQ_PASSWORD }}" >> .env
            echo "PGADMIN_EMAIL=${{ secrets.PROD_PGADMIN_EMAIL }}" >> .env
            echo "PGADMIN_PASSWORD=${{ secrets.PROD_PGADMIN_PASSWORD }}" >> .env
            echo "SEQ_PASSWORD=${{ secrets.PROD_SEQ_PASSWORD }}" >> .env
            echo "SMTP_PASSWORD=${{ secrets.PROD_SMTP_PASSWORD }}" >> .env
            
            docker compose down

            docker compose up -d --build