name: Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /root/ZXC
            git pull origin main

            docker compose down -v --remove-orphans

            docker system prune -f
            
            echo "PROD_DB_USER=${{ secrets.PROD_DB_USER }}" > .env
            echo "PROD_DB_PASSWORD=${{ secrets.PROD_DB_PASSWORD }}" >> .env
            echo "PROD_DB_NAME=${{ secrets.PROD_DB_NAME }}" >> .env
            echo "PROD_RABBITMQ_USER=${{ secrets.PROD_RABBITMQ_USER }}" >> .env
            echo "PROD_RABBITMQ_PASSWORD=${{ secrets.PROD_RABBITMQ_PASSWORD }}" >> .env
            echo "PROD_PGADMIN_EMAIL=${{ secrets.PROD_PGADMIN_EMAIL }}" >> .env
            echo "PROD_PGADMIN_PASSWORD=${{ secrets.PROD_PGADMIN_PASSWORD }}" >> .env
            echo "PROD_SEQ_PASSWORD=${{ secrets.PROD_SEQ_PASSWORD }}" >> .env
            echo "PROD_SMTP_PASSWORD=${{ secrets.PROD_SMTP_PASSWORD }}" >> .env
            echo "PROD_SMTP_USERNAME=${{ secrets.PROD_SMTP_USERNAME }}" >> .env
            echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> .env
            echo "PROD_SMTP_FROM=${{ secrets.PROD_SMTP_FROM }}" >> .env
            
            docker compose up -d --build --force-recreate --wait